### ISSUE TITLE
Install broken

### ISSUE THREAD

**Issue by fabvio** [vpj/lab_dashboard#8]
Hi. Since you moved the project to a new repository, the git submodule got broken, and in fact it cannot find the IO and weya libraries you were previously using.

**Comment by vpj** [comment]
Hey thanks a lot for catching this. I think I fixed it with https://github.com/lab-ml/dashboard/commit/93c97e8c89a966696200b06b0923ba5df0f32f67

**Comment by fabvio** [comment]
Yes, fixed!
